input_directory: "data/raw"
output_directory: "data/staging"
final_output_directory: "data/processed"
file_pattern: "*.csv"

transforms:
  # - remove_duplicates
  # - standardize_categories
  # - generate_mock_data
  - seperate_tables

categories:
  input_column: "original_category"
  output_column: "category_name"
