templates: 
  defaults: &defaults 
    page: 
      page_number: "all"
    dataframe: 
      header: False
      encoding: "utf-8-sig"
      index: Fale

websites: 
  tljus:
    path:
      website_path: https://tljus.com/
      save_path: web_etl_pipeline/data/urls/
    <<: *defaults
    scraping: 
      tag_name: nav
      menu_selector: dropdown-list-8 
      filter-keyword: None
      loading_type: single-page
      subcategory_selector: ""
      
      # tab-based navigation 
  breadtalk:
    path: 
      website_path: https://breadtalkvietnam.com/
      save_path: web_etl_pipeline/data/urls/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: menu-item  
      filter-keyword: product-category
      loading_type: pagination 
      pagination: 
        enabled: true
        next_selector: ".next"
        max_pages: 9999
        
  panacota: 
    path: 
      website_path: https://www.panacota.vn/
      save_path: web_etl_pipeline/data/urls/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: item-lv1
      filter-keyword: collections
      loading_type: progressive
      progressive_loading: 
        type: "load_more_button" # clicked-based progressive loading
        button_selector: ".loadmore-collection button"
        data_attributes: 
          product_count: "data-productcount"
          products_per_page: "data-paginate"

  cailonuong: 
    path: 
      website_path: https://cailonuong.com/
      save_path: web_etl_pipeline/data/urls/
    <<: *defaults
    scraping: 
      tag_name: ul
      menu_selector: sub-menu
      filter-keyword: danh-muc-san-pham
      loading_type: "single-page"