templates: 
  defaults: &defaults 
    page: 
      page_number: "all"
    # dataframe: 
    #   header: False
    #   encoding: "utf-8-sig"
    #   index: False

http: 
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0"

websites:
  # tljus:
  #   path:
  #     website_path: https://tljus.com/
  #     save_path: data/urls/
  #   <<: *defaults
  #   scraping: 
  #     tag_name: nav
  #     menu_selector: dropdown-list-8 
  #     filter-keyword: None

  #     # tab-based navigation 
  #     menu_type: "tabs"
  #     subcategory_selector: ".menu-tab"

  breadtalk:
    path: 
      website_path: https://breadtalkvietnam.com/
      save_path: data/urls/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: menu-item  
      filter-keyword: product-category

      loading_type: pagination 
      pagination: 
        next_selector: ".next"

      product_tag: a
      product_selector: .d-block

      product_detail_selectors:
        name: .entry-title 
        code: None 
        description: None 
        unit_price: p.price span.woocommerce-Price-amount bdi 
        image_selector: .swiper
        original_category: .posted_in
        
  panacota: 
    path: 
      website_path: https://www.panacota.vn/
      save_path: data/urls/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: item-lv1
      filter-keyword: collections

      loading_type: progressive
      button_selector: .loadmore-collection button
      
      product_tag: div
      product_selector: .product-block
      product_detail_selectors:
        name: .head-product-title
        code: .sku-number 
        description: .more-description
        unit_price: .price-now
        image_selector: .slick-list
        original_category: .pro-type

  cailonuong: 
    path: 
      website_path: https://cailonuong.com/
      save_path: data/urls/
    <<: *defaults
    scraping: 
      tag_name: ul
      menu_selector: sub-menu
      filter-keyword: danh-muc-san-pham
      
      product_tag: ul
      product_selector: .products 
      product_detail_selectors: 
        name: .product_title 
        code: None 
        description: .woocommerce-product-details__short-description
        unit_price: .price 
        image_selector: .slick-list
        original_category: .flex-control-thumbs 
