templates: 
  defaults: &defaults 
    page: 
      page_number: "all"
    # dataframe: 
    #   header: False
    #   encoding: "utf-8-sig"
    #   index: False

http: 
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0"

websites:
  tljus:
    path:
      website_path: https://tljus.com/
    <<: *defaults
    scraping: 
      tag_name: nav
      menu_selector: dropdown-list-8 
      filter-keyword: None

      loading_type: tab-based 
      subcategory_selector: .menu-tab
      skip_url_patterns: None 

      product_tag: div
      product_selector: .menu-item-single
      product_detail_selectors:
        name: .breadcrumb
        code: None 
        description: 
          - .menu-item-ingredients 
        unit_price: None 
        image_selector: .menu-item-main-image
        detail_image: None
        original_category: .cake-type 
        category_tag: div

  breadtalk:
    path: 
      website_path: https://breadtalkvietnam.com/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: menu-item  
      filter-keyword: product-category

      loading_type: pagination 
      pagination: 
        next_selector: ".next"
      product_tag: a
      product_selector: .d-block
      skip_url_patterns: None 

      product_detail_selectors:
        name: .entry-title 
        code: None 
        description: None 
        unit_price: p.price span.woocommerce-Price-amount bdi 
        image_selector: .swiper-wrapper 
        detail_image: .swiper-slide
        original_category: .posted_in
        category_tag: a
        
  panacota: 
    path: 
      website_path: https://www.panacota.vn/
    <<: *defaults
    scraping: 
      tag_name: li
      menu_selector: item-lv1
      filter-keyword: collections

      loading_type: progressive
      button_selector: .loadmore-collection button
      skip_url_patterns: None 

      product_tag: div
      product_selector: .product-block
      product_detail_selectors:
        name: .head-product-title
        code: .sku-number 
        description: 
          - .more-description
        unit_price: .price-now
        image_selector: .product-thumb
        detail_image: .product__thumbnail 
        original_category: .pro-type
        category_tag: a

  cailonuong: 
    path: 
      website_path: https://cailonuong.com/
    <<: *defaults
    scraping: 
      tag_name: ul
      menu_selector: sub-menu
      filter-keyword: danh-muc-san-pham
      
      product_tag: li
      product_selector: .product
      loading_type: single-page
      skip_url_patterns: "danh-muc-san-pham" 
      
      product_detail_selectors: 
        name: .product_title 
        code: None 
        description:
          - .woocommerce-product-details__short-description
          - .the_content_wrapper 
        unit_price: .price 
        image_selector: .woocommerce-product-gallery__wrapper
        detail_image: .woocommerce-product-gallery__image 
        original_category: .posted_in
        category_tag: a

  # thecoffeehouse: 
  #   path: 
  #     website_path: https://thecoffeehouse.com/collections/all
  #   <<: *defaults
  #   scraping: 
  #     tag_name: ul
  #     menu_selector: hidden-sm 
  #     filter-keyword: collections 
      
  #     product_tag: div
  #     product_selector: .menu_item_image
  #     loading_type: single-page
  #     skip_url_patterns: None  
      
  #     product_detail_selectors: 
  #       name: None 
  #       code: None 
  #       description: None 
  #       unit_price: None  
  #       image_selector: None 
  #       detail_image: None 
  #       original_category: None 
  #       category_tag: None 

  # igloo:
  #   path: 
  #     website_path: https://igloo.com.vn/
  #   <<: *defaults
  #   scraping: 
  #     tag_name: div
  #     menu_selector: None 
  #     filter-keyword: None

  #     loading_type: pagination
  #     pagination:
  #       next_selector: "a.page-link:contains(Next)" 

  #     product_tag: div
  #     product_selector: .product
  #     skip_url_patterns: None

  #     product_detail_selectors:
  #       name: .title-pro-detail
  #       code: None
  #       description: .desc-pro-detail
  #       unit_price: .price-new-pro-detail
  #       image_selector: .left-pro-detail
  #       detail_image: .MagicZoom
  #       original_category: "literal:Bingsu"
  #       category_tag: None  

  # seorbingsu: 
  #   path: 
  #     website_path: http://seorbingsu.vn/
  #   <<: *defaults
  #   scraping: 
  #     tag_name: div
  #     menu_selector: products-view
  #     filter-keyword: None 
      
  #     product_tag: div
  #     product_selector: .item_product_main
  #     loading_type: single-page
  #     skip_url_patterns: None  
      
  #     product_detail_selectors: 
  #       name: .title-product
  #       code: None 
  #       description: None 
  #       unit_price: .product-price  
  #       image_selector: .swiper-wrapper 
  #       detail_image: .swiper-slide 
  #       original_category: "literal:Topping thêm" 
  #       category_tag: None  

  # jenis: 
  #   path: 
  #     website_path: https://jenis.com/
  #   <<: *defaults
  #   scraping: 
  #     tag_name: None
  #     menu_selector: None
  #     filter-keyword: None
      
  #     product_tag: div
  #     product_selector: .container
  #     loading_type: single-page
  #     skip_url_patterns: None  
      
  #     product_detail_selectors: 
  #       name: .product-title
  #       code: None 
  #       description: .product-detail_description
  #       unit_price: .price__regular
  #       image_selector: .product-media-modal__content
  #       detail_image: img
  #       original_category: "literal:Ice cream" 
  #       category_tag: None

